version: "3.8"

services:
  langfuse:
    image: ghcr.io/langfuse/langfuse:latest
    restart: always
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://myuser:mypassword@db:5432/mydatabase2
      NEXTAUTH_URL: http://localhost:3000
      NEXTAUTH_SECRET: mysecret
      SALT: mysalt
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    build: ./postgres
    environment:
      POSTGRES_DB: mydatabase2
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - pgdata2:/var/lib/postgresql/data1
    ports:
      - "5430:5432"

volumes:
  pgdata2:
